### ISSUE TITLE
How to fix warning: Incompatible pointer types assigning to 'NSMutableArray<SyncEntity,ConvertOnDemand> *' from 'NSMutableArray *'

### ISSUE THREAD

**Issue by jbasttdi** [icanzilb/JSONModel#283]
I have this line of code that is giving me a warning:
```
    syncItem.syncEntityList=[[NSMutableArray alloc]init];
```
The warning is:
```
Incompatible pointer types assigning to 'NSMutableArray<SyncEntity,ConvertOnDemand> *' from 'NSMutableArray *'
```
```
@property(nonatomic,strong) NSMutableArray<SyncEntity,ConvertOnDemand> *syncEntityList;
```
The SyncEntity class:
```
#import <Foundation/Foundation.h>
#import "JSONModel.h"

@protocol SyncEntity @end

@interface SyncEntity : JSONModel
@property(strong,nonatomic) NSString *synctitle; 
@property(strong,nonatomic) NSString *syncrequestcode;   
@end
```
 Can someone please enlighten me?

**Comment by JoachimK** [comment]
The problem here is that JSONModel uses Objective-C protocols to declare specific attributes of the properties you specify in your model classes. However, this protocols also have a meaning for the compiler: The compiler now complains that a default NSMutableArray does not implement `ConvertOnDemand` or `SyncEntity`.
But none of these marker-protocols require any methods to be implemented, so you can safely cast your array to the appropriate protocol like this:

    syncItem.syncEntityList = (NSMutableArray<SyncEntity,ConvertOnDemand> *)[[NSMutableArray alloc] init];

**Comment by jbasttdi** [comment]
Cool,Best wish for you.

**Comment by FunnyCoderWang** [comment]
thanks ;-)

**Comment by billinghamj** [comment]
For anyone coming back to look at this, it is worth noting that `ConvertOnDemand` is no longer supported.
