### ISSUE TITLE
Parsing nested NSDictionary

### ISSUE THREAD

**Issue by hummer330** [icanzilb/JSONModel#296]
Hi just wondering whether jsonmodel can parse the json structure like this:

{
  "order_id": 104,
  "total_price": 13.45,
  "product": {
    "product 1": {
      "id": "123",
      "name": "Product name",
      "price": 12.95
    },
    "product 2": {
      "id": "123",
      "name": "Product name",
      "price": 12.95
    }
  }
}

**Comment by iOSCuriosity** [comment]
@hummer330  Yes. you can, but i'm afraid to use structure like "product1", "product2". I hope it does not change dynamically according to product quantity. Please use array instead of this structure for "product" key.

Here is the sample to produce JSONModel for this:

in Order.h,

@interface Order : JSONModel
@property (nonatomic) double totalPrice;
@property (nonatomic) NSInteger orderId;
@property (strong, nonatomic) OrderProduct *product;
@end

@interface OrderProduct : JSONModel
@property (strong, nonatomic) OrderProduct 1 *product 1;
@property (strong, nonatomic) OrderProduct 2 *product 2;
@end

@interface OrderProduct 2 : JSONModel
@property (nonatomic) double price;
@property (strong, nonatomic) NSString *id;
@property (strong, nonatomic) NSString *name;
@end

in Order.m,

@implementation Order
@end

@implementation OrderProduct
@end

@implementation OrderProduct 2
@end

@implementation OrderProduct 1
@end

**Comment by billinghamj** [comment]
JSONModel can handle dictionaries with dynamic keys, as follows:

```objc
@interface Order : JSONModel

@property (nonatomic) double totalPrice;
@property (nonatomic) NSInteger orderId;
@property (strong, nonatomic) NSDictionary <Product> *product;

@end

@interface Product : JSONModel

@property (nonatomic) double price;
@property (strong, nonatomic) NSString *id;
@property (strong, nonatomic) NSString *name;

@end
```
