### ISSUE TITLE
NSDecimalNumber should be serialized to NSString, not NSNumber

### ISSUE THREAD

**Issue by yanke-guo** [icanzilb/JSONModel#321]
Trying to serialize `NSDecimalNumber` to `JSON Number` will lead to float precision problem.

Currently, my solution is  to remove `NSDecimalNumber` from `allowedJSONTypes`, and add transformer methods:

```Objective-C
- (NSDecimalNumber*)NSDecimalNumberFromNSNumber:(NSNumber*)number;

- (id)JSONObjectFromNSDecimalNumber:(NSDecimalNumber*)number; // number.description
```

**Comment by billinghamj** [comment]
I think it's probably pretty debatable which behavior should be used, because it depends more on how the JSON is being deserialized on the other side. If you're using the right structures in the right language, you can use native JSON numbers without any risk of losing precision.

In my opinion, the way you're working around is the best thing to do and JSONModel's behavior should not change.
