### ISSUE TITLE
Bad property protocol declaration error when try to initialize the framework model class dervied from Jsonmodel 

### ISSUE THREAD

**Issue by vijayviswas** [icanzilb/JSONModel#366]
Hi ,
I created a framework which contains model class which is derived from jsonmodel. when I call initWithDictionary in app target & unittest target then I get below error.

[TestTests testPerformanceExample] : failed: caught "Bad property protocol declaration", "<Model class derived from Jsonmodel> is not allowed JSONModel property protocol, and not a JSONModel class."

for example. I have framework called XUtility.framework and the framework contains a model class named Operations which is dervied from Jsonmodel. Then I add this framework to a test project and try to initialize the framework model class.

**Comment by Rakesh-Azilen** [comment]
Me to facing same issue

**Comment by Rakesh-Azilen** [comment]
It seems that model classes that was in framework was not loaded before it was being initialized with dictionary, that's why

//few built-in transformations
-(id)__transform:(id)value forProperty:(JSONModelClassProperty*)property error:(NSError**)err
{
    Class protocolClass = NSClassFromString(property.protocol);
...........
}

"protocolClass" was Nil and the error was being thrown.

Solution was to simply add "-Objc" flag in Other linkers flag, so that classes can be loaded from static library before they get used.
