### ISSUE TITLE
Custom handling setter is not called when deserialising from JSON String or NSDictionary

### ISSUE THREAD

**Issue by sureal** [icanzilb/JSONModel#434]
Hi,

I have a class like:
@interface Response : JSONModel

@property (nonatomic, strong) NSString *dataType;
@property (strong, nonatomic) JSONModel *data;

and implement custom setters for the data property (which can be any subclass of JSONModel):

- (void) setDataWithNSString:(NSString *)string
{    
    JSONModelError* error = nil;
    self.data = [[[self dataTypeClass] alloc] initWithString:string error:&error];    
}

- (NSString *)JSONObjectForData
{
    return self.data.toJSONString;
}

But these custom setters get never called. Do I miss something or is this a bug?

My current workaround is implementing
- (instancetype)initWithDictionary:(NSDictionary *)dict error:(NSError **)error

which gets called and might work in the intended way, but I liked the custom setter thing more.
Would be happy to get it working this way.

ciao Matthias

**Comment by billinghamj** [comment]
If you have a structure like this:

```json
[
  { "type": "person", "name": "James", "sex": "M" },
  { "type": "company", "name": "Cuvva", "employees": 5 }
]
```

Then we'd generally recommend implementing a class cluster and automatically returning the correct type from `initWithDictionary` (see https://github.com/icanzilb/JSONModel/issues/229#issuecomment-52556421)

---

The above might not be relevant for you though. Could you please provide the JSON you're trying to deserialize?

With regards to potential bugs - it might be that the setter is not called for JSONModel subclasses.

**Comment by sureal** [comment]
Hi,

I already read #229 before raising this issue. It is working and it is the way I did implement it now, but I just wanted to report that the setters aren't called.

My JSON is a JSONObject as the most outer Structure: corresponding to the class 'Response'
{
data : { ... some serialized JSONModel subclass ...},
dataType : "MySubclass"
}

What I wanted to do first is to write the custom setter for the field data, which is a @property of class 'Response' with the type JSONModel (das data could be any subclass of JSONModel class)
Hence I wrote the (void) setDataWithNSString:(NSString )string 
where I used the Property dataType in order to get the class and calling initWithString: on it.
The could could have worked if the process of deserializing the 'Response' object would have triggered the call of setDataWithNSString.

If needed I could provide a small test project to let you see the issue. If the custom setters are deprecated please let me know.

ciao Matthias

**Comment by billinghamj** [comment]
Oke, so yeah the structure you have is a bit different from the one I mentioned above.

An issue I see with this is that there is no guarantee that `dataType` is set before the custom setter is called. So when your custom setter receives the data, you might not be able to create the correct object for it anyway.

Regardless, I believe the reason your custom setter isn't working is because the type isn't NSString - it's actually NSDictionary (since JSONModel deserializes into NSDictionary/NSArray objects before mapping data into the model classes).

So you should implement `setDataWithNSDictionary:`. Could you make this change and see if it works?

**Comment by sureal** [comment]
Hi, 
thanks I will try this and will let you know about the results. Your answer makes sense, I thought I would receive the JSON substring which is describing my JSONModel *data object but if the setter receives it already as a dictionary this is fine as well.
As you mentioned it, is there a deterministic order in which the properties get set on which I could rely? Best/easiest to understand would be in the order of declaration but as a bad workaround e.g. a alphabetical order would still be acceptable.
Anyway this may be also a use case for the lazy initialization of a JSONModel subclass instead of just supporting it for collection types, do you agree?

ciao Matthias

**Comment by billinghamj** [comment]
Let me know if it works using `setDataWithNSDictionary:`.

With regards to order of setting, I think we would probably strongly suggest not relying on it being consistent. This is because in the future, we may well make changes which remove any determinism - for example, calling setters concurrently, or making optimizations which could cause inconsistent ordering.

That being said, I think there are possibly other things we could do to allow for this, but I don't currently see any really obvious solutions.

**Comment by sureal** [comment]
Hi,

implementation of 
- (void)setDataWithNSDictionary:(NSDictionary*)dict {

gets called, so this is true. I think the examples are a bit to simple, as I was thinking one gets the JSONObject as a JSONString and not already parsed into a NSDictionary.
Anyway it is better the way as it is implemented now.

BUT: you are right: as I cannot rely on the order of deserialisation, indeed my dataType member is still nil when the setDataWithNSDictionary gets called.

So finally the solution for such a scenario of dependencies among the properties can only be solved by implementing - (instancetype)initWithDictionary:(NSDictionary *)dict error:(NSError **)error

Concerning this I found other issues which I will raise separately from this.
