### ISSUE TITLE
Feature request: expose __properties__ method to subclasses

### ISSUE THREAD

**Issue by boscomonkey** [icanzilb/JSONModel#440]
Would be nice if subclasses have access to the properties metadata that was gathered during init.

One use case is serialization to a remote store like Firebase, where an arbitrarily deep object graph should be stored in a flattened manner in order to deal with e.g., change notification, nesting limit, etc. With access to properties metadata, the FirebaseManager can easily determine which properties to replace with stubs during serialization, with the reverse operation upon deserialization.

This is a trivial change, but I'm not sure what the cons are. Would love to see a short discussion. And if folks think this should move ahead, I'll be happy to make the changes and send the PR.

**Comment by billinghamj** [comment]
I don't think we'd necessarily expose this data directly, because it would create restrictions around the changes we can make to the way JSONModel functions internally.

We would definitely be open to exposing some of the information through a separate interface though.

What specific info are you looking to use?

**Comment by billinghamj** [comment]
Closed due to inactivity.
