### ISSUE TITLE
JSONHTTPClient and JSONAPI return the session

### ISSUE THREAD

**Issue by Whirlwind** [icanzilb/JSONModel#450]
I want to cancel the network request after the view controller dealloc, but the JSONAPI do not return the session. 

I hope you can add it.

**Comment by billinghamj** [comment]
The HTTP functionality built into JSONModel is very basic and does not offer any advanced features. This is by design.

If you need to have any further control over the requests, you should use another framework, like AFNetworking or NSURLSession. JSONModel can be used with those for the (de)serialization part of the request.

**Comment by Whirlwind** [comment]
I know it. But I think the return value is a basic feature, the change is simple.

**Comment by billinghamj** [comment]
It's not going to happen. You're not meant to be doing anything complex with JSONModel's HTTP support. It does not aim to provide anything comprehensive.

The only reason it exists is as a convenience to people who are just starting out to reduce the barrier to entry of using JSONModel. If that wasn't the case, we wouldn't include the classes at all.
