### ISSUE TITLE
Crash on NSDecimalNumber

### ISSUE THREAD

**Issue by hugocroch** [icanzilb/JSONModel#455]
Hi, I have a JSON where one of my property is set as a NSDecimalNumber, but each time it tries to parse, it crashes and say that is not a supported type. Did I forgot something about the NSDecimalNumber? 

Thanks

**Comment by billinghamj** [comment]
I don't think JSONModel natively supports this. I suspect it might not be able to, due to how NSJSONSerialization works.

See: http://stackoverflow.com/a/21386112/743957

So the key thing you need to understand is: if you need the precision that NSDecimalNumber provides, you should not be using JSON numbers. You should instead use strings.

Let's assume your property declaration looks like this:

```objc
@property (nonatomic, strong) NSDecimalNumber *someDecimalNumber;
```

If you don't really need the precision, I guess you could implement a custom setter like:

```objc
- (void)setSomeDecimalNumberWithNSNumber:(NSNumber *)number
{
  _someDecimalNumber = [NSDecimalNumber decimalNumberWithDecimal:number.decimalValue];
}
```

If you were using strings, you'd do it this way:

```objc
- (void)setSomeDecimalNumberWithNSString:(NSString *)string
{
  _someDecimalNumber = [NSDecimalNumber decimalNumberWithString:string];
}
```

**Comment by ajumalebrahim** [comment]
I still get the issue after i used your second option. May be i am misunderstood. So my code is 
```
@interface ChoiceModel : JSONModel
@property (nonatomic, strong) NSDecimalNumber* discPrice;
@property (nonatomic, strong) NSDecimalNumber* price;
@end

@implementation ChoiceModel

+ (BOOL)propertyIsOptional:(NSString*)propertyName {
    return YES;
}

+ (JSONKeyMapper*)keyMapper {
    return [[JSONKeyMapper alloc] initWithDictionary:@{
                                                
                                                       @"itmpr": @"price",
                                                       @"itmopr": @"discPrice"
                                                       }];
}

- (void)setPriceWithNSString:(NSString *)string {
    _price = [NSDecimalNumber decimalNumberWithString:string];
}

- (void)setDiscPriceWithNSString:(NSString *)string {
    _discPrice = [NSDecimalNumber decimalNumberWithString:string];
}
@end
```
Can you help a bit. Thank you.

**Comment by billinghamj** [comment]
Could you provide a copy of your JSON?
