### ISSUE TITLE
Unable to override global mapperFromUnderscoreCaseToCamelCase

### ISSUE THREAD

**Issue by solarplexus6** [icanzilb/JSONModel#496]
I'm trying to override global mapperFromUnderscoreCaseToCamelCase with a mapper that just returns the key untouched (in a different API properties are in camel case). I'm unable to do so because of this line: https://github.com/icanzilb/JSONModel/blob/master/JSONModel/JSONModel/JSONModel.m#L270.

**Comment by billinghamj** [comment]
Then don't use a global key mapper. Instead you might want to have a root model class which you inherit from for all your models. e.g.:

```objc
@interface MyBaseModel : JSONModel
@end

@interface MyModel1 : MyBaseModel
@end

@interface MyModel2 : MyBaseModel
@end
```

```objc
@implementation MyBaseModel

+ (JSONKeyMapper *)keyMapper
{
  return [JSONKeyMapper mapperFromUnderscoreCaseToCamelCase];
}

@end

@ implementation MyModel2

+ (JSONKeyMapper *)keyMapper
{
  // override standard key mapper for this model only
  return nil;
}

@end
```

**Comment by solarplexus6** [comment]
That's a good suggestion, but I wanted to avoid changing all my models - there is quite many of them now.
More importantly - without further explanation I would treat the mentioned line as a bug. It's preventing me from overriding the global keymapper in this scenario (which isn't so uncommon) without any added value.

**Comment by billinghamj** [comment]
The global key mapper is there for convenience, but is not typically used in serious projects because it causes global pollution. Similarly, none of the JSONModel built-in networking code would be used by anything other than a hackathon-esque project. It's just there to help you get going more quickly.

I personally would be in favor of deprecating both features entirely, but that would depend on the opinions of the other maintainers.

The behavior of the line may well be considered unexpected, but it ultimately cannot be changed. Doing so is likely to break many projects.

**Comment by solarplexus6** [comment]
Fair enough, thanks for the explanation. Marking global mapper as depracated would certainly help to avoid confusion.
